// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreateOrderInput struct {
	Customer string            `json:"customer"`
	Items    []*OrderItemInput `json:"items"`
}

type CreatePizzaInput struct {
	Name        string                  `json:"name"`
	Price       float64                 `json:"price"`
	Ingredients []*PizzaIngredientInput `json:"ingredients"`
}

type Dashboard struct {
	TotalOrders       int     `json:"totalOrders"`
	CompletedToday    int     `json:"completedToday"`
	LowInventoryCount int     `json:"lowInventoryCount"`
	TotalRevenue      float64 `json:"totalRevenue"`
	BottomLine        float64 `json:"bottomLine"`
}

type Ingredient struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Unit        string  `json:"unit"`
	Current     int     `json:"current"`
	Max         int     `json:"max"`
	CostPerUnit float64 `json:"costPerUnit"`
}

type Mutation struct {
}

type Order struct {
	ID       string       `json:"id"`
	Customer string       `json:"customer"`
	Status   OrderStatus  `json:"status"`
	Revenue  float64      `json:"revenue"`
	Cost     float64      `json:"cost"`
	Items    []*OrderItem `json:"items"`
}

type OrderItem struct {
	PizzaID  string `json:"pizzaId"`
	Quantity int    `json:"quantity"`
}

type OrderItemInput struct {
	PizzaID  string `json:"pizzaId"`
	Quantity int    `json:"quantity"`
}

type Pizza struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Price       float64            `json:"price"`
	Ingredients []*PizzaIngredient `json:"ingredients"`
}

type PizzaIngredient struct {
	IngredientID string `json:"ingredientId"`
	Quantity     int    `json:"quantity"`
}

type PizzaIngredientInput struct {
	IngredientID string `json:"ingredientId"`
	Quantity     int    `json:"quantity"`
}

type Query struct {
}

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "PENDING"
	OrderStatusPreparing OrderStatus = "PREPARING"
	OrderStatusReady     OrderStatus = "READY"
	OrderStatusCompleted OrderStatus = "COMPLETED"
)

var AllOrderStatus = []OrderStatus{
	OrderStatusPending,
	OrderStatusPreparing,
	OrderStatusReady,
	OrderStatusCompleted,
}

func (e OrderStatus) IsValid() bool {
	switch e {
	case OrderStatusPending, OrderStatusPreparing, OrderStatusReady, OrderStatusCompleted:
		return true
	}
	return false
}

func (e OrderStatus) String() string {
	return string(e)
}

func (e *OrderStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderStatus", str)
	}
	return nil
}

func (e OrderStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
